const { section, subsection, bullet } = require('./util');

const skills = [
  {
    id: 'brand-invisibility-audit',
    title: 'Brand Invisibility Audit',
    shortDescription: 'Score your brand across messaging, visuals, and strategy.',
    description: 'Run a scored diagnostic across three dimensions — messaging, visual identity, and strategy — to expose exactly where your brand is blending into the background.',
    async run(prompter) {
      const inputs = {};
      inputs.tagline = await prompter.ask('Current tagline or value proposition');
      inputs.homepage = await prompter.ask('Homepage messaging or About page description');
      inputs.audience = await prompter.ask('Target audience description');
      inputs.competitors = await prompter.ask('Names of 2–3 direct competitors');
      inputs.feedback = await prompter.ask('Any feedback about being "similar" to others (optional)', { required: false });

      const messagingQuestions = [
        'Our value proposition could apply to 3+ competitors',
        'We use industry buzzwords in our marketing',
        'Our About page sounds like every other company in our space',
        'We lead with features, not unique outcomes',
      ];
      const visualQuestions = [
        'Our website/brand looks like industry templates',
        'Our colors match our competitors\' color schemes',
        'Our imagery is generic stock photos',
        'Our logo could work for any company in our space',
      ];
      const strategyQuestions = [
        'We target "everyone" in our market',
        'We compete mainly on price or "better service"',
        'We follow competitor strategies rather than setting our own',
        'We avoid taking controversial or polarizing positions',
      ];

      const ratings = {};
      console.log('\nRate each statement from 1 to 5:');
      console.log('  1 = That\'s definitely us (sameness danger)');
      console.log('  5 = That\'s never us (strongly differentiated)\n');

      for (const [index, question] of messagingQuestions.entries()) {
        ratings[`messaging${index + 1}`] = await prompter.askNumber(`Messaging ${index + 1}: ${question}`, { min: 1, max: 5 });
      }
      for (const [index, question] of visualQuestions.entries()) {
        ratings[`visual${index + 1}`] = await prompter.askNumber(`Visual ${index + 1}: ${question}`, { min: 1, max: 5 });
      }
      for (const [index, question] of strategyQuestions.entries()) {
        ratings[`strategy${index + 1}`] = await prompter.askNumber(`Strategy ${index + 1}: ${question}`, { min: 1, max: 5 });
      }

      const messagingScore = Object.keys(ratings)
        .filter((k) => k.startsWith('messaging'))
        .reduce((sum, k) => sum + ratings[k], 0);
      const visualScore = Object.keys(ratings)
        .filter((k) => k.startsWith('visual'))
        .reduce((sum, k) => sum + ratings[k], 0);
      const strategyScore = Object.keys(ratings)
        .filter((k) => k.startsWith('strategy'))
        .reduce((sum, k) => sum + ratings[k], 0);
      const totalScore = messagingScore + visualScore + strategyScore;

      let diagnosis;
      let nextStep;
      if (totalScore >= 48) {
        diagnosis = 'You\'re already standing out — rare. Sharpen, don\'t rebuild.';
        nextStep = 'positioning-health-check';
      } else if (totalScore >= 36) {
        diagnosis = 'You have some differentiation but it\'s fragile. Competitors can close the gap.';
        nextStep = 'anti-positioning-generator';
      } else if (totalScore >= 24) {
        diagnosis = 'You\'re blending in. Customers see you as interchangeable. This is urgent.';
        nextStep = 'blue-ocean-mapper';
      } else {
        diagnosis = 'You\'re invisible. Same message, same look, same strategy. Repositioning is not optional.';
        nextStep = 'order-winners-finder';
      }

      const lowestDimension = [
        { name: 'Messaging', score: messagingScore },
        { name: 'Visual', score: visualScore },
        { name: 'Strategy', score: strategyScore },
      ].sort((a, b) => a.score - b.score)[0];

      const allQuestions = [
        ...messagingQuestions.map((q, i) => ({ q, score: ratings[`messaging${i + 1}`], dim: 'Messaging' })),
        ...visualQuestions.map((q, i) => ({ q, score: ratings[`visual${i + 1}`], dim: 'Visual' })),
        ...strategyQuestions.map((q, i) => ({ q, score: ratings[`strategy${i + 1}`], dim: 'Strategy' })),
      ];
      const traps = allQuestions.sort((a, b) => a.score - b.score).slice(0, 3);

      let output = `# Brand Invisibility Audit Report\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Tagline: ${inputs.tagline}`) + '\n';
      output += bullet(`Homepage/About: ${inputs.homepage}`) + '\n';
      output += bullet(`Audience: ${inputs.audience}`) + '\n';
      output += bullet(`Competitors: ${inputs.competitors}`) + '\n';
      if (inputs.feedback) output += bullet(`Feedback: ${inputs.feedback}`) + '\n';

      output += section('Audit Scores');
      output += bullet(`Messaging Score: ${messagingScore} / 20`) + '\n';
      output += bullet(`Visual Score: ${visualScore} / 20`) + '\n';
      output += bullet(`Strategy Score: ${strategyScore} / 20`) + '\n';
      output += bullet(`Total Score: ${totalScore} / 60`) + '\n';

      output += section('Diagnosis');
      output += `${diagnosis}\n\n`;
      output += `The dimension bleeding the most is **${lowestDimension.name}** (${lowestDimension.score}/20).\n`;

      output += section('Three Biggest Sameness Traps');
      for (const trap of traps) {
        output += bullet(`${trap.dim}: "${trap.q}" — scored ${trap.score}/5`) + '\n';
      }

      output += section('Recommended Next Step');
      output += `Run \`${nextStep}\` to address the biggest gaps.\n`;

      output += section('Prompt to Synthesize Further');
      output += `Copy the report above into an AI assistant and ask: "Based on this Brand Invisibility Audit, write a brutal one-paragraph summary of why this brand is blending in, expand the three sameness traps with specific recommendations tied to the inputs above, and recommend the exact next skill to run."\n`;

      return output;
    },
  },
  {
    id: 'order-winners-finder',
    title: 'Order Winners Finder',
    shortDescription: 'Find what actually makes customers choose you over alternatives.',
    description: 'Separate genuine differentiators from table stakes. Identify the 1–2 things that actually drive buying decisions.',
    async run(prompter) {
      const inputs = {};
      inputs.product = await prompter.ask('Product or service description (what you sell and to whom)');
      inputs.features = await prompter.ask('List 8–12 features or benefits you currently market');
      inputs.quotes = await prompter.ask('Customer quotes or feedback, especially "why did you choose us?" (optional)', { required: false });
      inputs.competitors = await prompter.ask('Main competitors (optional)', { required: false });

      let output = `# Order Winners Finder Worksheet\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Product/service: ${inputs.product}`) + '\n';
      output += bullet(`Features/benefits: ${inputs.features}`) + '\n';
      if (inputs.quotes) output += bullet(`Customer quotes: ${inputs.quotes}`) + '\n';
      if (inputs.competitors) output += bullet(`Competitors: ${inputs.competitors}`) + '\n';

      output += section('Classification Table');
      output += `Use this table to classify each feature as Table Stake (T) or Order Winner (O).\n\n`;
      output += `| Feature/Benefit | T or O | Why |\n`;
      output += `|-----------------|--------|-----|\n`;
      for (const feature of inputs.features.split(/\n|,/).map((f) => f.trim()).filter(Boolean)) {
        output += `| ${feature} | | |\n`;
      }

      output += section('So What Test');
      output += `For each Order Winner candidate, apply the "So What?" test twice to reach the real customer outcome.\n`;
      output += bullet(`Feature → So what? → So what? → Verdict`) + '\n';

      output += section('Primary Order Winner');
      output += `Identify the single most powerful differentiator — the one that, if removed from your marketing, would make you indistinguishable.\n`;

      output += section('Where to Lead With It');
      output += bullet('Homepage headline') + '\n';
      output += bullet('Elevator pitch opening') + '\n';
      output += bullet('Sales deck first slide') + '\n';

      output += section('Prompt to Complete With AI');
      output += `Copy this worksheet into an AI assistant and ask: "Take these features and classify each as Table Stake or Order Winner. Run the So What test on the top 3 candidates, name the single Primary Order Winner, and tell me exactly where to lead with it in my marketing."\n`;

      return output;
    },
  },
  {
    id: 'blue-ocean-mapper',
    title: 'Blue Ocean Mapper',
    shortDescription: 'Map competitive white space and find territory nobody has claimed.',
    description: 'Build a perceptual map of your market, plot competitors, and identify the empty quadrants.',
    async run(prompter) {
      const inputs = {};
      inputs.product = await prompter.ask('Your product or service and target market');
      inputs.competitors = await prompter.ask('Names of up to 5 direct competitors');
      inputs.positions = await prompter.ask('One-sentence description of what each competitor stands for');
      inputs.feedback = await prompter.ask('Customer feedback about why they chose you over alternatives (optional)', { required: false });

      const axisPairs = [
        'Price (Low ↔ High) vs. Complexity (Simple ↔ Complex)',
        'Speed (Slow ↔ Fast) vs. Customization (Generic ↔ Bespoke)',
        'Accessibility (Exclusive ↔ Mass Market) vs. Prestige (Commodity ↔ Premium)',
        'Technology (Manual ↔ Automated) vs. Human Touch (Transactional ↔ Relational)',
        'Scope (Narrow ↔ Broad) vs. Depth (Surface ↔ Deep Expertise)',
      ];
      const axisChoice = await prompter.askChoice('Choose the two axes for your perceptual map', axisPairs);

      let output = `# Blue Ocean Mapper Worksheet\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Product/service: ${inputs.product}`) + '\n';
      output += bullet(`Competitors: ${inputs.competitors}`) + '\n';
      output += bullet(`Competitor positions: ${inputs.positions}`) + '\n';
      if (inputs.feedback) output += bullet(`Customer feedback: ${inputs.feedback}`) + '\n';
      output += bullet(`Axes: ${axisChoice}`) + '\n';

      output += section('Perceptual Map');
      output += `Plot each competitor and your brand on the 2×2 grid below.\n\n`;
      output += `\`\`\`\n`;
      output += `High [Axis Y]\n`;
      output += `     ↑\n`;
      output += `     |   [Empty?]      [Competitor C]\n`;
      output += `     |\n`;
      output += `     |\n`;
      output += `Low  ←————————————————————→  High [Axis X]\n`;
      output += `     |\n`;
      output += `     |   [Your Brand]   [Competitor A]\n`;
      output += `     |                  [Competitor B]\n`;
      output += `     ↓\n`;
      output += `Low [Axis Y]\n`;
      output += `\`\`\`\n`;

      output += section('White Space Assessment');
      output += `For each empty quadrant, answer:\n`;
      output += bullet('Why is it empty?') + '\n';
      output += bullet('Is there latent demand?') + '\n';
      output += bullet('Can you credibly claim it?') + '\n';
      output += bullet('Is it defensible?') + '\n';

      output += section('Blue Ocean Move');
      output += `State the single best repositioning direction as a specific claim, not a quadrant label.\n`;

      output += section('Prompt to Complete With AI');
      output += `Copy this worksheet into an AI assistant and ask: "Build a perceptual map from these inputs, identify the best empty quadrant, run the four White Space questions, and recommend a specific Blue Ocean move with a one-sentence positioning direction."\n`;

      return output;
    },
  },
  {
    id: 'value-bucket-builder',
    title: 'Value Bucket Builder',
    shortDescription: 'Extract functional, emotional, social, and aspirational value.',
    description: 'Excavate all four value dimensions and assemble them into a brand promise that captures what customers actually experience.',
    async run(prompter) {
      const inputs = {};
      inputs.product = await prompter.ask('Your product or service and target customer');
      inputs.description = await prompter.ask('How you currently describe what you do (website copy, elevator pitch, tagline)');
      inputs.testimonials = await prompter.ask('Customer testimonials or "why did you choose us?" responses (optional)', { required: false });
      inputs.referrals = await prompter.ask('What your best customers say when they refer others (optional)', { required: false });

      let output = `# Value Bucket Builder Worksheet\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Product/service: ${inputs.product}`) + '\n';
      output += bullet(`Current description: ${inputs.description}`) + '\n';
      if (inputs.testimonials) output += bullet(`Testimonials: ${inputs.testimonials}`) + '\n';
      if (inputs.referrals) output += bullet(`Referral quotes: ${inputs.referrals}`) + '\n';

      output += section('The Four Value Buckets');
      output += subsection('Functional Value');
      output += bullet('Primary function: What does the product do in one sentence?') + '\n';
      output += bullet('Key performance metric: What measurable outcome does it produce?') + '\n';
      output += bullet('Practical outcome: What problem disappears when customers use it?') + '\n';

      output += subsection('Emotional Value');
      output += bullet('Primary emotion delivered: What is the dominant emotional shift?') + '\n';
      output += bullet('During use: How do they feel while engaging with the product?') + '\n';
      output += bullet('After results: What is the emotional payoff once it works?') + '\n';

      output += subsection('Social Value');
      output += bullet('Identity signal: What does choosing this product say about the customer?') + '\n';
      output += bullet('Community: What group does it connect them to?') + '\n';
      output += bullet('External perception: How do others view them differently?') + '\n';

      output += subsection('Aspirational Value');
      output += bullet('Future self: Who does the customer become through using this?') + '\n';
      output += bullet('Transformation: What meaningful change does it enable over time?') + '\n';
      output += bullet('New capability: What can they do after that they could not before?') + '\n';

      output += section('So What Pressure Test');
      output += `Apply the "So what?" test twice to each bucket to get past surface-level answers.\n`;

      output += section('Brand Promise');
      output += `Use the formula:\n\n`;
      output += `> We help [target] achieve [functional outcome] so they can [emotional/social/aspirational outcome] without [traditional friction/cost].\n`;

      output += section('Prompt to Complete With AI');
      output += `Copy this worksheet into an AI assistant and ask: "Fill in the four value buckets with specific, non-generic answers, run the So What pressure test, and assemble 2–3 brand promise options using the formula. Recommend which version to lead with and why."\n`;

      return output;
    },
  },
  {
    id: 'anti-positioning-generator',
    title: 'Anti-Positioning Generator',
    shortDescription: 'Build bold "we\'re not for you" messaging.',
    description: 'Create exclusion statements that repel wrong-fit customers and magnetize the right ones.',
    async run(prompter) {
      const inputs = {};
      inputs.ideal = await prompter.ask('Your ideal customer profile (who you do your best work with)');
      inputs.worst = await prompter.ask('Your worst client experiences — what made them bad fits');
      inputs.churn = await prompter.ask('Patterns in customers who churn or complain (optional)', { required: false });
      inputs.positioning = await prompter.ask('Your current positioning or value proposition (optional)', { required: false });
      inputs.pricing = await prompter.askChoice('Pricing tier', ['Premium', 'Mid-market', 'Budget']);

      let output = `# Anti-Positioning Generator Worksheet\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Ideal customer: ${inputs.ideal}`) + '\n';
      output += bullet(`Worst-fit experiences: ${inputs.worst}`) + '\n';
      if (inputs.churn) output += bullet(`Churn/complaint patterns: ${inputs.churn}`) + '\n';
      if (inputs.positioning) output += bullet(`Current positioning: ${inputs.positioning}`) + '\n';
      output += bullet(`Pricing tier: ${inputs.pricing}`) + '\n';

      output += section('Who You Do Not Serve');
      output += `Identify 4–6 wrong-fit customer types across these categories:\n`;
      output += bullet('Price sensitivity mismatches') + '\n';
      output += bullet('Expectation mismatches') + '\n';
      output += bullet('Values mismatches') + '\n';
      output += bullet('Scale or stage mismatches') + '\n';

      output += section('Exclusion Statements');
      output += `Use the template: "We\'re not for [type] who [behavior]. We\'re for [ideal] who [behavior]."\n\n`;
      output += `Write 4–6 statements and stack them from soft to sharp.\n`;

      output += section('Placement Map');
      output += `| Channel | Statement intensity |\n`;
      output += `|---------|---------------------|\n`;
      output += `| Website homepage | Soft or medium |\n`;
      output += `| Pricing page | Medium |\n`;
      output += `| Sales conversations | Sharp |\n`;
      output += `| Content / social | Sharp |\n`;
      output += `| Customer onboarding | Medium |\n`;
      output += `| Email sequences | Soft or medium |\n`;

      output += section('One-Line Declaration');
      output += `Distill the full set into one line: "Not for [them]. For [you]."\n`;

      output += section('Prompt to Complete With AI');
      output += `Copy this worksheet into an AI assistant and ask: "Based on these inputs, identify 4–6 wrong-fit customer types, write exclusion statements using the template, stack them from soft to sharp, map them to channels, and produce the final one-line anti-positioning declaration."\n`;

      return output;
    },
  },
  {
    id: 'ai-positioning-sprint',
    title: 'AI Positioning Sprint',
    shortDescription: 'Run the complete 25-minute positioning workflow.',
    description: 'Three stages, three positioning angles, one clear direction — from blue ocean discovery to weakness-to-strength reframes to category creation.',
    async run(prompter) {
      const inputs = {};
      inputs.competitors = await prompter.ask('Top 5 direct competitors (names only is fine)');
      inputs.messaging = await prompter.ask('Your current brand messaging and value propositions');
      inputs.feedback = await prompter.ask('Customer feedback about why people chose you over alternatives (optional)', { required: false });
      inputs.unique = await prompter.ask('Your product\'s unique characteristics — especially things you consider weaknesses');

      let output = `# AI Positioning Sprint Worksheet\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Competitors: ${inputs.competitors}`) + '\n';
      output += bullet(`Current messaging: ${inputs.messaging}`) + '\n';
      if (inputs.feedback) output += bullet(`Customer feedback: ${inputs.feedback}`) + '\n';
      output += bullet(`Unique characteristics: ${inputs.unique}`) + '\n';

      output += section('Stage 1: Competitive Landscape Scan');
      output += `| Competitor | Main Positioning | Key Benefits Claimed | Target Audience |\n`;
      output += `|------------|------------------|----------------------|-----------------|\n`;
      output += `| Your Brand | | | |\n`;
      for (const competitor of inputs.competitors.split(/\n|,/).map((c) => c.trim()).filter(Boolean)) {
        output += `| ${competitor} | | | |\n`;
      }

      output += section('Stage 2: Three Positioning Angles');
      output += subsection('Angle A: Blue Ocean Discovery');
      output += `Find 3 positioning angles no competitor currently claims. Each should reframe the buying decision.\n`;
      output += subsection('Angle B: Weakness-to-Strength');
      output += `Reframe 3 apparent disadvantages as strategic advantages.\n`;
      output += subsection('Angle C: Category Creation');
      output += `Name a new category and write the old-vs-new narrative.\n`;

      output += section('Stage 3: Selection and Rollout');
      output += `Evaluate angles by: Authenticity, Credibility, Appetite, Longevity.\n\n`;
      output += `| Channel | What Changes | When |\n`;
      output += `|---------|--------------|------|\n`;
      output += `| Homepage headline | | This week |\n`;
      output += `| Elevator pitch | | This week |\n`;
      output += `| Social bio | | This week |\n`;
      output += `| Sales deck opening | | 30 days |\n`;
      output += `| Content themes | | 30 days |\n`;
      output += `| Customer onboarding | | 30 days |\n`;

      output += section('Prompt to Complete With AI');
      output += `Copy this worksheet into an AI assistant and ask: "Run the full 25-minute positioning sprint. Fill the competitive landscape table, identify the commodity trap, deliver three Blue Ocean angles, three weakness-to-strength reframes, category creation messaging with a category name, recommend the strongest direction, and fill the rollout plan."\n`;

      return output;
    },
  },
  {
    id: 'category-creator',
    title: 'Category Creator',
    shortDescription: 'Name and own a new market category.',
    description: 'Stop competing in existing categories. Name and own a new one so comparisons become irrelevant.',
    async run(prompter) {
      const inputs = {};
      inputs.product = await prompter.ask('Your current product/service and what category you\'re currently placed in');
      inputs.competitors = await prompter.ask('3–5 competitors who currently define that category');
      inputs.broken = await prompter.ask('What\'s broken or outdated about how the market thinks about this problem?');
      inputs.customers = await prompter.ask('How your best customers describe what you do (optional)', { required: false });
      inputs.conviction = await prompter.ask('What you believe that your competitors don\'t — your founding conviction');

      let output = `# Category Creator Worksheet\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Product/service and current category: ${inputs.product}`) + '\n';
      output += bullet(`Competitors defining the category: ${inputs.competitors}`) + '\n';
      output += bullet(`What\'s broken/outdated: ${inputs.broken}`) + '\n';
      if (inputs.customers) output += bullet(`Customer language: ${inputs.customers}`) + '\n';
      output += bullet(`Founding conviction: ${inputs.conviction}`) + '\n';

      output += section('Step 1: Current Category Dismantled');
      output += bullet('Old definition: How does the market currently describe this category?') + '\n';
      output += bullet('Default script: What promises does every competitor make?') + '\n';
      output += bullet('What\'s missing: What does the current category ignore?') + '\n';
      output += bullet('Why it\'s outdated: What has changed technologically, culturally, or behaviorally?') + '\n';

      output += section('Step 2: The Market Shift');
      output += `What\'s changed that makes a new category timely and inevitable?\n`;

      output += section('Step 3: Category Name Options');
      output += `Generate 3–5 category names. For each, include definition, why it matters, and how it differs.\n`;

      output += section('Step 4: Category Ownership Assets');
      output += bullet('Category narrative: 2–3 sentences on why this category exists') + '\n';
      output += bullet('Messaging pillars: 3–5 core beliefs defining membership') + '\n';
      output += bullet('Flag-planting statement: one declarative line establishing ownership') + '\n';

      output += section('Step 5: Then vs. Now Framing');
      output += `Write 2–3 contrasts that make the old category feel outdated.\n`;

      output += section('Prompt to Complete With AI');
      output += `Copy this worksheet into an AI assistant and ask: "Dismantle the current category, articulate the market shift, generate 3–5 category names with rationale and select the strongest, write category ownership assets, and produce then-vs-now framing statements."\n`;

      return output;
    },
  },
  {
    id: 'customer-journey-optimizer',
    title: 'Customer Journey Optimizer',
    shortDescription: 'Find and fix friction points across your customer funnel.',
    description: 'Map the emotional and psychological journey, identify drop-offs, and build specific interventions to fix them.',
    async run(prompter) {
      const inputs = {};
      inputs.stages = await prompter.ask('Your customer journey stages (find → become a customer)');
      inputs.rates = await prompter.ask('Conversion rates at each major stage (optional)', { required: false });
      inputs.dropoffs = await prompter.ask('Where you see the biggest drop-offs');
      inputs.feedback = await prompter.ask('Customer feedback about why they did not move forward (optional)', { required: false });
      inputs.process = await prompter.ask('What your sales/onboarding process looks like');

      let output = `# Customer Journey Optimizer Worksheet\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Journey stages: ${inputs.stages}`) + '\n';
      if (inputs.rates) output += bullet(`Conversion rates: ${inputs.rates}`) + '\n';
      output += bullet(`Biggest drop-offs: ${inputs.dropoffs}`) + '\n';
      if (inputs.feedback) output += bullet(`Feedback: ${inputs.feedback}`) + '\n';
      output += bullet(`Sales/onboarding process: ${inputs.process}`) + '\n';

      output += section('Journey Map');
      output += `| Stage | What Happens | Conversion Rate | Known Drop-off Reasons |\n`;
      output += `|-------|--------------|-----------------|------------------------|\n`;
      for (const stage of inputs.stages.split(/\n|,/).map((s) => s.trim()).filter(Boolean)) {
        output += `| ${stage} | | | |\n`;
      }

      output += section('Friction Dimensions');
      output += `For the 2–3 worst drop-offs, analyze across:\n`;
      output += bullet('Cognitive Load') + '\n';
      output += bullet('Trust Barriers') + '\n';
      output += bullet('Information Gaps') + '\n';
      output += bullet('Process Complexity') + '\n';
      output += bullet('Emotional Hesitations') + '\n';
      output += bullet('Competitive Alternatives') + '\n';

      output += section('Intervention Plan');
      output += `| Friction Point | What to Add/Remove | Messaging to Use | How to Measure |\n`;
      output += `|----------------|--------------------|------------------|----------------|\n`;
      output += `| | | | |\n`;
      output += `| | | | |\n`;
      output += `| | | | |\n`;

      output += section('Emotional Journey Map');
      output += `| Stage | Emotional State | Primary Driver | What Shifts Them Forward |\n`;
      output += `|-------|-----------------|---------------|--------------------------|\n`;
      output += `| | | | |\n`;

      output += section('Prompt to Complete With AI');
      output += `Copy this worksheet into an AI assistant and ask: "Map the journey, identify the biggest bleeding point, analyze the top 3 friction points across the six dimensions, build a specific intervention plan sorted by effort-to-impact, and map the emotional journey with what shifts customers forward at each stage."\n`;

      return output;
    },
  },
  {
    id: 'positioning-health-check',
    title: 'Positioning Health Check',
    shortDescription: 'Quarterly audit to check if your positioning is still working.',
    description: 'Run a structured quarterly review to catch drift before it becomes a crisis.',
    async run(prompter) {
      const inputs = {};
      inputs.positioning = await prompter.ask('Your current positioning statement or how you describe what makes you different');
      inputs.competitors = await prompter.ask('Top 3–5 competitors');
      inputs.shifts = await prompter.ask('Recent market shifts (new competitors, category changes, customer behavior changes)');
      inputs.trends = await prompter.ask('Conversion rate trends over the last 2–3 quarters (improving, flat, declining)');
      inputs.feedback = await prompter.ask('Customer feedback patterns — what are customers saying more or less of?');
      inputs.messagingChanges = await prompter.ask('Any competitors who have recently changed their messaging (optional)', { required: false });

      console.log('\nScore each dimension as: Strong, Drifting, or Eroded.\n');
      const dimensions = ['Market Position', 'Message Effectiveness', 'Competitive Landscape', 'Evolution Triggers'];
      const scores = {};
      for (const dim of dimensions) {
        scores[dim] = await prompter.askChoice(`Score: ${dim}`, ['Strong', 'Drifting', 'Eroded']);
      }

      let overall;
      const counts = { Strong: 0, Drifting: 0, Eroded: 0 };
      Object.values(scores).forEach((s) => counts[s]++);
      if (counts.Eroded > 0) {
        overall = 'Eroding — active repositioning required. Run ai-positioning-sprint.';
      } else if (counts.Drifting >= 3) {
        overall = 'Eroding — active repositioning required. Run ai-positioning-sprint.';
      } else if (counts.Drifting >= 1) {
        overall = 'Drifting — sharpen specific dimensions before drift becomes erosion.';
      } else {
        overall = 'Strong — maintain and defend. Document what is working.';
      }

      let output = `# Positioning Health Check Report\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      output += bullet(`Current positioning: ${inputs.positioning}`) + '\n';
      output += bullet(`Competitors: ${inputs.competitors}`) + '\n';
      output += bullet(`Market shifts: ${inputs.shifts}`) + '\n';
      output += bullet(`Conversion trends: ${inputs.trends}`) + '\n';
      output += bullet(`Customer feedback patterns: ${inputs.feedback}`) + '\n';
      if (inputs.messagingChanges) output += bullet(`Competitor messaging changes: ${inputs.messagingChanges}`) + '\n';

      output += section('Health Scores');
      for (const [dim, score] of Object.entries(scores)) {
        output += bullet(`${dim}: ${score}`) + '\n';
      }

      output += section('Overall Positioning Health');
      output += `${overall}\n`;

      output += section('Action Plan');
      output += bullet('This week: quick fixes and messaging adjustments') + '\n';
      output += bullet('This quarter: structural repositioning if needed') + '\n';
      output += bullet('Watch list: things to monitor that have not become problems yet') + '\n';

      output += section('Next Check-In');
      output += `Schedule the next health check in 90 days. Watch conversion trends, competitor messaging, and customer language alignment.\n`;

      output += section('Prompt to Synthesize Further');
      output += `Copy this report into an AI assistant and ask: "Based on this Positioning Health Check, identify the most critical finding, expand the action plan with specific tasks for this week and this quarter, and recommend whether to hold, sharpen, or evolve the positioning."\n`;

      return output;
    },
  },
  {
    id: 'stand-out-blueprint',
    title: 'Stand-Out Blueprint',
    shortDescription: 'Synthesize everything into a one-page deployable brand strategy.',
    description: 'Assemble positioning, anti-positioning, value buckets, and category thinking into a one-page brand strategy document.',
    async run(prompter) {
      const mode = await prompter.askChoice('Build mode', [
        'Synthesis — I have outputs from other Stand the F*ck Out skills',
        'Cold Build — I am starting from scratch',
      ]);

      const inputs = {};
      if (mode.startsWith('Synthesis')) {
        inputs.context = await prompter.ask('Paste the key outputs from other skills you want synthesized (optional)', { required: false });
      }
      inputs.target = await prompter.ask('Target customer (who specifically)');
      inputs.problem = await prompter.ask('Their core problem — the one you solve better than anyone');
      inputs.approach = await prompter.ask('Your unique approach to solving it');
      inputs.differentiators = await prompter.ask('Your 1–2 genuine differentiators');
      inputs.notFor = await prompter.ask('Who is this explicitly NOT for?');
      inputs.refuse = await prompter.ask('What will you refuse to compete on?');
      inputs.functional = await prompter.ask('Primary functional outcome');
      inputs.emotional = await prompter.ask('Primary emotional outcome');
      inputs.identity = await prompter.ask('What identity or aspiration does this serve?');
      inputs.oldCategory = await prompter.ask('What category do you compete in today?');
      inputs.newCategory = await prompter.ask('What category do you want to own?');
      inputs.brandName = await prompter.ask('Brand name (optional)', { required: false });

      let output = `# Stand-Out Blueprint\n`;
      output += `Generated by stand-the-fuck-out CLI\n\n`;
      output += section('Inputs');
      if (inputs.context) output += bullet(`Context from other skills: ${inputs.context}`) + '\n';
      output += bullet(`Target customer: ${inputs.target}`) + '\n';
      output += bullet(`Core problem: ${inputs.problem}`) + '\n';
      output += bullet(`Unique approach: ${inputs.approach}`) + '\n';
      output += bullet(`Differentiators: ${inputs.differentiators}`) + '\n';
      output += bullet(`Not for: ${inputs.notFor}`) + '\n';
      output += bullet(`Refuse to compete on: ${inputs.refuse}`) + '\n';
      output += bullet(`Functional outcome: ${inputs.functional}`) + '\n';
      output += bullet(`Emotional outcome: ${inputs.emotional}`) + '\n';
      output += bullet(`Identity/aspiration: ${inputs.identity}`) + '\n';
      output += bullet(`Old category: ${inputs.oldCategory}`) + '\n';
      output += bullet(`New category: ${inputs.newCategory}`) + '\n';
      if (inputs.brandName) output += bullet(`Brand name: ${inputs.brandName}`) + '\n';

      output += section('Blueprint Sections');
      output += subsection('1. Positioning Statement');
      const brand = inputs.brandName || '[Brand Name]';
      output += `For ${inputs.target} who ${inputs.problem}, ${brand} is the ${inputs.newCategory} that ${inputs.approach} unlike ${inputs.oldCategory} competitors who ${inputs.refuse}.\n`;

      output += subsection('2. Brand Promise');
      output += `We help ${inputs.target} achieve ${inputs.functional} so they can ${inputs.emotional} / ${inputs.identity} without ${inputs.refuse}.\n`;

      output += subsection('3. Anti-Positioning Declaration');
      output += bullet(`We are NOT for: ${inputs.notFor}`) + '\n';
      output += bullet(`We ARE for: ${inputs.target}`) + '\n';

      output += subsection('4. Core Differentiators');
      output += bullet(`${inputs.differentiators}`) + '\n';

      output += subsection('5. Value Proposition (Four Buckets)');
      output += bullet(`Functional: ${inputs.functional}`) + '\n';
      output += bullet(`Emotional: ${inputs.emotional}`) + '\n';
      output += bullet(`Social: ${inputs.identity}`) + '\n';
      output += bullet(`Aspirational: ${inputs.identity}`) + '\n';

      output += subsection('6. Category Ownership');
      output += bullet(`Old category: ${inputs.oldCategory}`) + '\n';
      output += bullet(`New category: ${inputs.newCategory}`) + '\n';
      output += bullet(`Flag-planting statement: We are building ${inputs.newCategory}, not competing in ${inputs.oldCategory}.`) + '\n';

      output += subsection('7. Implementation Priorities');
      output += bullet('This week: update homepage headline, elevator pitch, social bios, add anti-positioning statement') + '\n';
      output += bullet('30 days: redesign marketing materials, create content around new positioning, update onboarding, brief team') + '\n';
      output += bullet('90 days: launch category creation content, develop case studies, complete visual update, set positioning metrics') + '\n';

      output += section('Quality Check');
      output += bullet('Is the positioning statement specific enough that a competitor could not claim it without lying?') + '\n';
      output += bullet('Does the anti-positioning exclude someone real?') + '\n';
      output += bullet('Are the differentiators genuinely differentiating, not category table stakes?') + '\n';
      output += bullet('Does the category name feel owned, not generic?') + '\n';

      output += section('Prompt to Synthesize Further');
      output += `Copy this blueprint into an AI assistant and ask: "Review this Stand-Out Blueprint against the quality check, sharpen any generic sections, rewrite the positioning statement and brand promise in 2–3 alternative phrasings, and finalize the implementation priorities for my specific situation."\n`;

      return output;
    },
  },
];

module.exports = skills;
